CREATE DATABASE FASHION
USE  FASHION

CREATE TABLE BRANDS(B_ID INT PRIMARY KEY IDENTITY, B_NAME VARCHAR(20), ITEM_TYPE VARCHAR(20), PRICE NUMERIC(10), SIZE TEXT)

INSERT INTO BRANDS VALUES ('GUCCI', 'CLOTHS', 10000, 'L')
INSERT INTO BRANDS VALUES ('NIKE', 'SHOES', 5000, 'ALL')
INSERT INTO BRANDS VALUES ('MANISH', 'CLOTHS', 10500, 'ALL')
INSERT INTO BRANDS VALUES ('MOCHI', 'SHOES', 10550, 'L')
INSERT INTO BRANDS VALUES ('ZARA', 'COSMATICS', 19000, 'ALL')
INSERT INTO BRANDS VALUES ('NAYKA', 'BEAUTY', 10000, 'L')
INSERT INTO BRANDS VALUES ('WOODLAND', 'SHOES', 15000, 'ALL')
INSERT INTO BRANDS VALUES ('JACK', 'CLOTHS', 1000, 'L')
INSERT INTO BRANDS VALUES ('MUFTI', 'CLOTHS', 18000, 'ALL')
INSERT INTO BRANDS VALUES ('HRX', 'CLOTHS', 1050, 'ALL')

SELECT * FROM BRANDS

CREATE TABLE CELEBRITY(C_ID INT PRIMARY KEY IDENTITY(101,1), C_NAME VARCHAR(20), PHONENO NUMERIC(10))

INSERT INTO CELEBRITY VALUES ('SARUKH', 1234567897)
INSERT INTO CELEBRITY VALUES ('AKSHAY', 123456767)
INSERT INTO CELEBRITY VALUES ('SALMAN', 123455677)
INSERT INTO CELEBRITY VALUES ('ALIA', 1234568987)
INSERT INTO CELEBRITY VALUES ('KATRINA', 12457697)
INSERT INTO CELEBRITY VALUES ('VARUN', 123567987)
INSERT INTO CELEBRITY VALUES ('RITIK', 124567345)
INSERT INTO CELEBRITY VALUES ('HEMA', 124556497)
INSERT INTO CELEBRITY VALUES ('DEPIKA', 137657897)
INSERT INTO CELEBRITY VALUES ('SARUKH', 239757897)

SELECT * FROM CELEBRITY

CREATE TABLE ENDORSEMENT(E_ID INT PRIMARY KEY IDENTITY(1001,1), C_ID INT, B_ID INT)

INSERT INTO ENDORSEMENT VALUES (101,1)
INSERT INTO ENDORSEMENT VALUES (102,2)
INSERT INTO ENDORSEMENT VALUES (103,3)
INSERT INTO ENDORSEMENT VALUES (104,4)
INSERT INTO ENDORSEMENT VALUES (105,5)
INSERT INTO ENDORSEMENT VALUES (106,6)
INSERT INTO ENDORSEMENT VALUES (107,7)
INSERT INTO ENDORSEMENT VALUES (108,8)
INSERT INTO ENDORSEMENT VALUES (109,9)
INSERT INTO ENDORSEMENT VALUES (110,10)
INSERT INTO ENDORSEMENT VALUES (101,5)
INSERT INTO ENDORSEMENT VALUES (101,8)
INSERT INTO ENDORSEMENT VALUES (103,6)
INSERT INTO ENDORSEMENT VALUES (109,1)
INSERT INTO ENDORSEMENT VALUES (104,1)
INSERT INTO ENDORSEMENT VALUES (108,3)
INSERT INTO ENDORSEMENT VALUES (106,1)
INSERT INTO ENDORSEMENT VALUES (107,5)
INSERT INTO ENDORSEMENT VALUES (107,5)
INSERT INTO ENDORSEMENT VALUES (105,10)

SELECT * FROM ENDORSEMENT

CREATE VIEW INFO 
AS 
SELECT E_ID,C_ID,B_ID FROM ENDORSEMENT AS E
FULL JOIN
BRANDS AS B
ON E.B_ID = B.B_ID

SELECT * FROM INFO


CREATE PROCEDURE sp_BRANDENDORSED
AS
BEGIN
SELECT B.B_ID, B.B_NAME, E.C_ID
FROM BRANDS AS B 
FULL JOIN
ENDORSEMENT AS E
ON B.B_ID = E.B_ID
END

EXEC sp_BRANDENDORSED



CREATE PROCEDURE sp_BRANDNOTENDORSED
AS
BEGIN
SELECT B.B_ID, B.B_NAME, E.C_ID
FROM BRANDS AS B 
LEFT JOIN
ENDORSEMENT AS E
ON B.B_ID = E.B_ID
END

EXEC sp_BRANDNOTENDORSED



CREATE PROCEDURE sp_COMMONBRANDENDORSED
AS
BEGIN
SELECT B.B_ID, B.B_NAME, E.C_ID
FROM BRANDS AS B 
INNER JOIN
ENDORSEMENT AS E
ON B.B_ID = E.B_ID
END

EXEC sp_COMMONBRANDENDORSED





